Repository fjordllc/bootcamp, pull requests merged in 2020-09, with the labels that each got.

#1850 プラクティスごとの日報、Q&A、提出物一覧に認証を追加
  app/controllers/practices/products_controller.rb
  app/controllers/practices/questions_controller.rb
  app/controllers/practices/reports_controller.rb
Labels: バグ

#1852 卒業証書機能を削除
  app/assets/stylesheets/diploma.sass
  app/controllers/admin/diploma_controller.rb
  app/views/admin/diploma/show.html.slim
  app/views/admin/users/_table.html.slim
  app/views/layouts/diploma.html.slim
  config/initializers/assets.rb
  config/routes.rb
  test/system/admin/diploma_test.rb
Labels: 雑事

#1853 DEPRECATEDになっているgemを削除
  Gemfile
  Gemfile.lock
Labels: 雑事

#1858 chartkickを削除
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  app/views/admin/home/index.html.slim
  app/views/application/_header_links.html.slim
  package.json
  yarn.lock
Labels: 雑事

#1865 提出物が作成されたときにメンターがWatchしないようにした
  app/models/product_callbacks.rb
Labels: 新機能

#1870 サブスクの状況を管理画面で見れるようにした
  app/controllers/admin/users_controller.rb
  app/decorators/user_decorator.rb
  app/models/subscription.rb
  app/views/admin/users/_table.html.slim
  config/locales/ja.yml
  test/application_system_test_case.rb
  test/models/subscription_test.rb
  test/supports/stub_helper.rb
Labels: 新機能

#1872 slack通知処理をcontrollerからmodelに変更
  app/controllers/pages_controller.rb
  app/models/page_callbacks.rb
Labels: 雑事

#1881 APIでHTMLをエスケープしないようにした
  app/views/api/reports/recents/index.json.jbuilder
  test/fixtures/reports.yml
Labels: バグ

#1916 Net::OpenTimeoutもrescueすることにした
  app/models/link_checker.rb
Labels: バグ

#1919 mentorへのメンション記法を追加
  app/javascript/markdown-it-mention.js
  app/models/concerns/mentioner.rb
Labels: 5, 新機能

#1939 メンテナンスページを追加
  public/maintenance.html
Labels: 雑事
