Repository fjordllc/bootcamp, pull requests merged in 2020-11, with the labels that each got.

#2062 リンクチェッカーを修正
  app/controllers/scheduler/link_checker_controller.rb
  app/controllers/scheduler/statistic_controller.rb
  app/controllers/scheduler/statistics_controller.rb
  app/controllers/scheduler_controller.rb
  app/jobs/notice_slack_job.rb
  app/models/link_checker.rb
  app/models/link_checker/checker.rb
  app/models/link_checker/extractor.rb
  config/routes.rb
  test/fixtures/pages.yml
  test/fixtures/practices.yml
  test/models/link_checker/checker_test.rb
  test/models/link_checker/extractor_test.rb
Labels: バグ

#2064 リンク切れ通知のフォーマットが間違ってたのを修正
  app/models/link_checker/checker.rb
Labels: バグ

#2070 存在しないURLなどに対応
  app/models/link_checker/extractor.rb
  test/models/link_checker/extractor_test.rb
Labels: バグ

#2089 空のカテゴリーが表示されていたのを修正。
  app/views/welcome/practices.html.slim
Labels: バグ

#2100 markdownのlinkのマッチ方法を修正
  app/models/link_checker/extractor.rb
  test/models/link_checker/extractor_test.rb
Labels: バグ

#2102 エラー表示を追加
  app/models/link_checker/checker.rb
Labels: 雑事

#2105 schedulerのメソッドをPATCHからGETにした
  app/controllers/scheduler/link_checker_controller.rb
  app/controllers/scheduler/statistic_controller.rb
  app/models/link_checker/checker.rb
  config/routes.rb
Labels: 雑事

#2106 同時実行スレッドを5に制限
  app/models/link_checker/checker.rb
Labels: 雑事

#2107 urlから空白を除去
  app/models/link_checker/extractor.rb
Labels: バグ

#2108 amazonに集中アクセスしないようにした
  app/models/link_checker/checker.rb
Labels: バグ

#2109 リタイアページを認証必須にした
  app/controllers/retirement_controller.rb
Labels: バグ

#2112 escapeを削除
  app/models/link_checker/checker.rb
Labels: 雑事

#2113 invalidなURLで止まらないようにした
  app/models/link_checker/checker.rb
Labels: バグ

#2114 invalid urlでエラーが起きるのを修正
  app/models/link_checker/checker.rb
Labels: バグ

#2116 clientを別クラスにした
  app/models/link_checker/checker.rb
  app/models/link_checker/client.rb
  test/models/link_checker/checker_test.rb
  test/models/link_checker/client_test.rb
Labels: 雑事

#2117 日本語部分だけescapeするように修正
  app/models/link_checker/client.rb
  test/models/link_checker/client_test.rb
Labels: バグ

#2120 cache storeをmemoryに戻した
  Gemfile
  Gemfile.lock
  config/environments/production.rb
Labels: 雑事

#2122 VPC Connectorの設定を削除
  cloudbuild.yaml
Labels: 雑事

#2132 secretがないときのJWT secretを設定
  config/initializers/sorcery.rb
Labels: バグ

#2133 VPC Connectorの設定を解除
  cloudbuild.yaml
Labels: バグ

#2134 clear vpcの記述を削除
  cloudbuild.yaml
Labels: 雑事

#2124 管理者はDocのユーザーを変更できる
  app/controllers/pages_controller.rb
  app/views/pages/_form.html.slim
  config/locales/ja.yml
  test/system/pages_test.rb
Labels: 新機能

#2136 data-migrate gemを追加
  Gemfile
  Gemfile.lock
  cloudbuild.yaml
  db/data/20201122113956_change_komagata.rb
  db/data_schema.rb
  db/schema.rb
Labels: 雑事

#2151 metric関連を削除
  app/controllers/admin/home_controller.rb
  app/models/metric/user.rb
Labels: 雑事

#2164 commentがきたら必ず通知するようにした
  app/models/comment_callbacks.rb
Labels: バグ
