Repository fjordllc/bootcamp, pull requests merged in 2021-04, with the labels that each got.

#2538 静的ファイルを配信
  Dockerfile
  cloudbuild.yaml
Labels: 1, 雑事

#2544 画像変換を通すようにした
  app/models/company.rb
  app/models/user.rb
  app/models/work.rb
  config/application.rb
  config/storage.yml
Labels: 1, 雑事

#2558 slack通知を削除
  app/controllers/users_controller.rb
Labels: バグ

#2563 link_checkerにmockを追加
  test/fixtures/files/mock_bodies/developer.mozilla.org.html
  test/fixtures/files/mock_bodies/docs.komagata.org.html
  test/fixtures/files/mock_bodies/e-words.jp.html
  test/fixtures/files/mock_bodies/example.com.html
  test/fixtures/files/mock_bodies/pc-master.jp.html
  test/models/link_checker/checker_test.rb
  test/models/link_checker/client_test.rb
  test/supports/stub_helper.rb
Labels: 雑事

#1740 Q&AのQをページ遷移なしで編集できるように変更
  app/assets/stylesheets/atoms/_a-page-notice.sass
  app/assets/stylesheets/blocks/card/_card-footer.sass
  app/assets/stylesheets/blocks/form/_form-tabs-item.sass
  app/assets/stylesheets/blocks/form/_form-tabs.sass
  app/assets/stylesheets/blocks/page/_page-notice.sass
  app/assets/stylesheets/blocks/thread/_thread-form.sass
  app/assets/stylesheets/blocks/thread/_thread-questions.sass
  app/controllers/api/practices_controller.rb
  app/controllers/api/questions_controller.rb
  app/controllers/questions_controller.rb
  app/javascript/answer.vue
  app/javascript/answers.js
  app/javascript/answers.vue
  app/javascript/mentor_memo.vue
  app/javascript/packs/application.js
  app/javascript/question-edit.vue
  app/javascript/question.js
  app/javascript/question.vue
  app/javascript/question_tags.js
  app/javascript/question_tags.vue
  app/javascript/user-icon.vue
  app/views/api/practices/index.json.jbuilder
  app/views/api/questions/show.json.jbuilder
  app/views/questions/edit.html.slim
  app/views/questions/new.html.slim
  app/views/questions/show.html.slim
  app/views/users/index.html.slim
  app/views/users/show.html.slim
  config/locales/ja.yml
  config/routes.rb
  db/fixtures/questions.yml
  test/fixtures/questions.yml
  test/integration/api/practices_test.rb
  test/integration/api/questions_test.rb
  test/system/questions_test.rb
Labels: 5

#2575 stagingへのデプロイ時にDBをresetするようにした
  lib/tasks/bootcamp.rake
Labels: 1, 雑事

#2579 Cloud Runのメモリ使用量を増やした
  cloudbuild.yaml
Labels: 1, 雑事

#2644 GWキャンペーン
  app/assets/stylesheets/welcome/_welcome-section_is-gw.sass
  app/views/welcome/_about.slim
  app/views/welcome/_campaign.html.slim
  app/views/welcome/index.html.slim
Labels: 1, 雑事

#2647 ブログロゴのブートキャンプの説明を追加
  app/assets/stylesheets/article.sass
  app/views/articles/index.html.slim
  app/views/articles/show.html.slim
  app/views/layouts/article.html.slim
  test/system/articles_test.rb
Labels: 1, 新機能
