Repository fjordllc/bootcamp, pull requests merged in 2021-06, with the labels that each got.

#2763 personal tokenを追加
  .github/workflows/create-issue-register-kanban.yml
Labels: 1, 雑事

#2510 担当になるボタンを表示するページでサイズを選択できるようにしたい
  app/javascript/check.vue
  app/javascript/product_checker.vue
Labels: 2, バグ

#2782 Q&AのQの投稿者とログイン中ユーザーが同じになっている問題を修正
  app/javascript/question.vue
  config/environments/development.rb
Labels: バグ

#2841 ユーザーの提出物一覧をログイン必須にした
  app/controllers/users/products_controller.rb
  app/controllers/users/questions_controller.rb
  app/controllers/users/tags_controller.rb
  test/system/login_requirements_test.rb
Labels: 1, バグ

#2853 JSのバグを修正
  app/controllers/api/tags_controller.rb
  app/views/application/_current_user.html.erb
Labels: 1, バグ

#2863 webmockからVCRに変更
  .circleci/config.yml
  .github/stale.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  README.md
  app/models/customer.rb
  app/models/customer_stub.rb
  app/models/github_grass.rb
  app/models/subscription.rb
  app/models/subscription_stub.rb
  lib/tasks/fixtures.rake
  test/application_system_test_case.rb
  test/cassettes/customer/create.yml
  test/cassettes/customer/list.yml
  test/cassettes/customer/update.yml
  test/cassettes/github_grass/fetch.yml
  test/cassettes/link_checker/checker/check.yml
  test/cassettes/link_checker/client/request/developer_mozilla_org.yml
  test/cassettes/link_checker/client/request/e-words_jp.yml
  test/cassettes/link_checker/client/request/example_com.yml
  test/cassettes/link_checker/client/request/fjord_jp.yml
  test/cassettes/plan/list.yml
  test/cassettes/sign_up/declined-card.yml
  test/cassettes/sign_up/expired-card.yml
  test/cassettes/sign_up/incorrect-cvc-card.yml
  test/cassettes/sign_up/valid-card.yml
  test/cassettes/subscription/create.yml
  test/cassettes/subscription/list.yml
  test/cassettes/subscription/retrieve.yml
  test/cassettes/subscription/update.yml
  test/cassettes/token/create.yml
  test/fixtures/files/mock_bodies/customer.json
  test/fixtures/files/mock_bodies/developer.mozilla.org.html
  test/fixtures/files/mock_bodies/docs.komagata.org.html
  test/fixtures/files/mock_bodies/e-words.jp.html
  test/fixtures/files/mock_bodies/example.com.html
  test/fixtures/files/mock_bodies/pc-master.jp.html
  test/fixtures/files/mock_bodies/subscription.json
  test/integration/api/announcements_test.rb
  test/models/card_test.rb
  test/models/github_grass_test.rb
  test/models/link_checker/checker_test.rb
  test/models/link_checker/client_test.rb
  test/models/plan_test.rb
  test/models/practice_test.rb
  test/models/product_test.rb
  test/models/subscription_test.rb
  test/supports/stub_helper.rb
  test/system/companies_test.rb
  test/system/products_test.rb
  test/system/reports_test.rb
  test/system/retirement_test.rb
  test/system/sign_up_test.rb
  test/system/welcome_test.rb
  test/test_helper.rb
Labels: 雑事

#2873 CIのときのテスト並列実行数を増やした
  test/supports/vcr_helper.rb
  test/test_helper.rb
Labels: 雑事

#2896 開発環境でインデックス名が衝突しているのを修正
  db/migrate/20201203035119_add_index_to_reactions.rb
  db/schema.rb
Labels: 1, バグ
