Repository fjordllc/bootcamp, pull requests merged in 2022-01, with the labels that each got.

#3955 デプロイ時に本番環境でvalidationが通らないのを修正
  db/data/20211217030634_add_option_to_notified_retirement.rb
  test/system/events_test.rb
Labels: バグ, 1

#3988 skylightを削除
  Gemfile
  Gemfile.lock
  cloudbuild.yaml
  config/skylight.yml
Labels: 雑事, 1

#3993 READMEに通知機能についてのリンクを追加
  README.md
Labels: 雑事, 1

#3994 お知らせのテストをリファクタリング
  app/views/announcements/_form.html.slim
  test/system/notification/announcements_test.rb
Labels: 雑事

#4003 cloudbuild用の処理を削除
  lib/tasks/bootcamp.rake
Labels: 雑事

#4005 Cloud Build 用タスクで #3936 の動作確認に必要なテストデータを作成できるようにした
  lib/tasks/bootcamp.rake
Labels: 雑事

#4013 コメントのFlakyなテストを修正
  app/javascript/answers.vue
  app/javascript/comment-placeholder.vue
  app/javascript/comments.js
  app/javascript/comments.vue
  test/system/api/check/products_test.rb
  test/system/comments_test.rb
  test/system/followings_test.rb
  test/system/reports_test.rb
Labels: 雑事

#4033 テストデータが不正だったのを修正
  test/fixtures/users.yml
Labels: 雑事

#4058 ステージングで実行するためのtaskを作成
  lib/tasks/bootcamp.rake
Labels: 雑事, 1
