Repository fjordllc/bootcamp, pull requests merged in 2022-03, with the labels that each got.

#4365 相談部屋の内容が検索結果に現れないようにした
  app/models/searcher.rb
  test/fixtures/comments.yml
  test/models/searcher_test.rb
Labels: バグ, 1

#4383 DiscordのWebhookのENVを追加
  .cloudbuild/cloudbuild.yaml
Labels: 雑事

#4379 Rename test/system/notification/after_retirement.rb
  test/system/notification/after_retirement_test.rb
Labels: 1

#4423 相談のコメントではメンションをしないように修正
  app/models/concerns/mentioner.rb
  test/models/comment_test.rb
Labels: バグ

#4425 相談のコメントではメンションをしないように修正
  app/models/concerns/mentioner.rb
  test/models/comment_test.rb
Labels: バグ

#4404 プライバシーポリシーにGoogleアナリティクスとRollbarについてを追加
  app/views/welcome/_pp.html.slim
Labels: 雑事

#4430 接続している全ユーザーを切断するrake taskを追加
  lib/tasks/bootcamp.rake
Labels: 雑事
