Repository fjordllc/bootcamp, pull requests merged in 2022-07, with the labels that each got.

#5204 提出物一覧ページでコメントしたユーザーのアイコンの色が適切に表示されないバグを修正
  app/javascript/product.vue
  app/views/api/products/_product.json.jbuilder
Labels: バグ

#5199 休会機能を追加
  app/assets/stylesheets/atoms/_a-block-check.sass
  app/assets/stylesheets/atoms/_a-text.sass
  app/assets/stylesheets/blocks/form/_block-checks.sass
  app/assets/stylesheets/blocks/form/_important-message.sass
  app/assets/stylesheets/variables/_colors.sass
  app/controllers/api/users_controller.rb
  app/controllers/hibernation_controller.rb
  app/controllers/user_sessions_controller.rb
  app/mailers/notification_mailer.rb
  app/models/hibernation.rb
  app/models/notification.rb
  app/models/notification_facade.rb
  app/models/user.rb
  app/notifiers/activity_notifier.rb
  app/notifiers/discord_notifier.rb
  app/views/admin/users/_nav.html.slim
  app/views/hibernation/new.html.slim
  app/views/hibernation/show.html.slim
  app/views/notification_mailer/hibernated.html.slim
  app/views/static_pages/retire.html.slim
  app/views/users/_hibernation_info.html.slim
  app/views/users/show.html.slim
  config/locales/ja.yml
  config/routes.rb
  db/fixtures/hibernations.yml
  db/fixtures/notifications.yml
  db/fixtures/talks.yml
  db/fixtures/users.yml
  db/migrate/20220705074430_add_hibernated_at_to_users.rb
  db/migrate/20220705085844_create_hibernations.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/users.yml
  test/mailers/previews/notification_mailer_preview.rb
  test/models/user_test.rb
  test/system/hibernation_test.rb
Labels: 新機能

#5264 落ちやすいテストをいくつか修正
  app/views/announcements/_announcement.html.slim
  app/views/pages/_doc_header.html.slim
  app/views/pages/show.html.slim
  test/system/announcements_test.rb
  test/system/notification/assigned_as_checker_test.rb
  test/system/pages_test.rb
Labels: 雑事

#5284 自分のコースに無いプラクティスの提出物画面でのエラーを修正
  app/models/category.rb
Labels: バグ
