Repository fjordllc/bootcamp, pull requests merged in 2022-08, with the labels that each got.

#5303 よく落ちるテストを修正
  test/application_system_test_case.rb
Labels: 雑事

#5305 decoratorのテスト名を他と統一した
  test/decorators/user_decorator_test.rb
Labels: 雑事

#5308 データ投入の順番がおかしかったのを修正
  db/seeds.rb
Labels: バグ

#5338 Invalidなユーザーをチェックするページを追加
  app/controllers/scheduler/validator_controller.rb
  config/routes/scheduler.rb
  lib/tasks/bootcamp.rake
Labels: 雑事

#5376 invalidなユーザーをDiscordに通知する様に修正
  app/controllers/scheduler/validator_controller.rb
  app/notifiers/discord_notifier.rb
  test/notifiers/discord_notifier_test.rb
Labels: 雑事

#5367 提出物と日報を確認済みにすると「日報を確認済みにしました」と表示される
  app/javascript/checkable.js
Labels: バグ, 2

#5455 minitest-ciを導入
  .circleci/config.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  test/application_system_test_case.rb
Labels: 雑事
