Repository fjordllc/bootcamp, pull requests merged in 2023-01, with the labels that each got.

#6029 CircleCIでテストが動かない問題を修正
  .circleci/config.yml
Labels: 雑事

#6063 卒業通知が2回行われていた問題を修正
  app/deliveries/activity_delivery.rb
  test/deliveries/activity_delivery_test.rb
Labels: バグ

#6070 メール受信を拒否していても卒業メールが送られてしまう問題を修正
  app/mailers/activity_mailer.rb
  test/mailers/activity_mailer_test.rb
Labels: バグ, 1

#6136 reports.ymlファイルにおける2023年問題の解決
  db/fixtures/reports.yml
  test/fixtures/reports.yml
Labels: 1
